#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════
//  AjayaDesign — Portfolio Card Injector
//  Reads client JSON from stdin, generates a portfolio card,
//  and injects it into index.html before the %%PORTFOLIO_INJECT%% marker.
//
//  Usage: echo '{"repoName":"...","clientName":"...","niche":"...","goals":"...","emoji":"...","indexPath":"..."}' | node inject_card.js
// ═══════════════════════════════════════════════════════════════
const fs = require('fs');

let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', chunk => { input += chunk; });
process.stdin.on('end', () => {
  let data;
  try {
    data = JSON.parse(input);
  } catch (e) {
    console.error('❌ inject_card.js: Invalid JSON input');
    process.exit(1);
  }

  const { repoName, clientName, niche, goals, emoji, indexPath } = data;

  if (!repoName || !clientName || !indexPath) {
    console.error('❌ inject_card.js: repoName, clientName, and indexPath are required');
    process.exit(1);
  }

  // HTML-escape helper
  const esc = s => (s || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

  const safeName = esc(clientName);
  const safeNiche = esc(niche || 'General');
  const shortGoals = esc(goals || '').substring(0, 50);
  const descGoals = esc(goals || '').substring(0, 120);
  const safeEmoji = emoji || '🌐';

  const card = `
        <!-- Project — ${safeName} (auto-generated by pipeline) -->
        <a href="/${repoName}/" target="_blank" rel="noopener noreferrer" class="reveal group block rounded-2xl bg-surface-card border border-border-dim overflow-hidden hover:border-amd-red/40 transition-all duration-300 hover:-translate-y-1">
          <!-- Browser chrome -->
          <div class="flex items-center gap-2 px-4 py-2.5 border-b border-border-dim bg-surface-alt/50">
            <span class="w-2 h-2 rounded-full bg-red-500/60"></span>
            <span class="w-2 h-2 rounded-full bg-yellow-500/60"></span>
            <span class="w-2 h-2 rounded-full bg-green-500/60"></span>
            <span class="ml-2 flex-1 text-center font-mono text-xs text-gray-400 truncate">ajayadesign.github.io/${repoName}</span>
          </div>
          <!-- Preview area -->
          <div class="relative h-44 bg-gradient-to-br from-surface via-surface-alt to-surface-card flex items-center justify-center overflow-hidden">
            <div class="absolute inset-0 bg-gradient-to-br from-blue-900/10 via-transparent to-amd-red/5"></div>
            <div class="relative text-center px-4">
              <span class="text-3xl">${safeEmoji}</span>
              <p class="mt-2 font-mono text-xs text-gray-400">${shortGoals}</p>
            </div>
            <!-- Hover overlay -->
            <div class="absolute inset-0 bg-amd-red/0 group-hover:bg-amd-red/10 transition-colors duration-300 flex items-center justify-center">
              <span class="opacity-0 group-hover:opacity-100 transition-opacity duration-300 font-mono text-xs text-white bg-amd-red/80 px-3 py-1.5 rounded">View Live Site →</span>
            </div>
          </div>
          <!-- Info -->
          <div class="p-5">
            <h3 class="font-mono text-base font-bold text-white mb-2 group-hover:text-amd-red transition-colors">${safeName}</h3>
            <p class="text-gray-400 text-sm leading-relaxed mb-4">${descGoals}</p>
            <div class="flex flex-wrap gap-2 font-mono text-xs">
              <span class="px-2 py-1 rounded bg-surface-alt border border-border-dim text-gray-400">${safeNiche}</span>
            </div>
          </div>
        </a>
`;

  // Read index.html and inject before marker
  const MARKER = '<!-- %%PORTFOLIO_INJECT%% -->';

  if (!fs.existsSync(indexPath)) {
    console.error(`❌ inject_card.js: File not found: ${indexPath}`);
    process.exit(1);
  }

  let html = fs.readFileSync(indexPath, 'utf8');

  if (!html.includes(MARKER)) {
    console.error(`❌ inject_card.js: Marker "${MARKER}" not found in ${indexPath}`);
    process.exit(1);
  }

  html = html.replace(MARKER, card.trimEnd() + '\n\n        ' + MARKER);
  fs.writeFileSync(indexPath, html);

  console.log(`✅ Portfolio card for "${clientName}" injected into ${indexPath}`);
});
